# Generated by Django 4.2.2 on 2023-06-17 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_phoneverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='phone_number_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='PhoneVerification',
        ),
    ]
