# Generated by Django 4.2.2 on 2023-06-19 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_customuser_phone_number_verified_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='phone_number_verified',
        ),
    ]
