# Generated by Django 4.2.2 on 2023-06-22 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_productlike_product_likes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productlike',
            old_name='username',
            new_name='user',
        ),
        migrations.AlterUniqueTogether(
            name='productlike',
            unique_together={('product', 'user')},
        ),
    ]
