# Generated by Django 4.2.2 on 2023-06-22 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_favorite'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favorite',
        ),
    ]
