# Generated by Django 4.2.2 on 2023-07-04 08:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_favorite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='description',
            new_name='full_description',
        ),
        migrations.AddField(
            model_name='product',
            name='short_description',
            field=models.TextField(default=datetime.datetime(2023, 7, 4, 8, 55, 11, 941202, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
